parameters:
  page_media_set.page_media_set_service.class: ArsThanea\PageMediaSetBundle\Service\PageMediaSetService
  page_media_set.format_repository.class: ArsThanea\PageMediaSetBundle\Service\FormatRepository
  page_media_set.node_listener.class: ArsThanea\PageMediaSetBundle\EventListener\PageMediaSetFormAdaptorListener
  page_media_set.form.page_media_admin_type.class: ArsThanea\PageMediaSetBundle\Form\PageMediaAdminType
  page_media_set.twig.page_media_set_twig_extension.class: ArsThanea\PageMediaSetBundle\Twig\PageMediaSetTwigExtension
  page_media_set.media_set_definition.class: 'ArsThanea\PageMediaSetBundle\Service\MediaSetDefinitionService'

services:
  page_media_set.page_media_set_service:
    class: %page_media_set.page_media_set_service.class%
    arguments: [ '@page_media_set.repository', '@page_media_set.media_set_definition' ]

  page_media_set.format_repository:
    class: %page_media_set.format_repository.class%
    public: false

  page_media_set.repository:
    class: ArsThanea\PageMediaSetBundle\Entity\PageMediaRepository
    factory:
      - @doctrine.orm.entity_manager
      - getRepository
    arguments:
      - ArsThanea\PageMediaSetBundle\Entity\PageMedia

  page_media_set.twig.page_media_set_twig_extension:
    class: %page_media_set.twig.page_media_set_twig_extension.class%
    arguments: [ @page_media_set.page_media_set_service ]
    public: false
    tags:
      - { name: twig.extension }

  page_media_set.node_listener:
    class: %page_media_set.node_listener.class%
    arguments: [ '@page_media_set.repository', '@page_media_set.media_set_definition' ]
    tags:
      - { name: kernel.event_listener, event: kunstmaan_node.adaptForm, method: adaptForm }

  page_media_set.form.page_media_admin_type:
    class: %page_media_set.form.page_media_admin_type.class%
    arguments: [ @page_media_set.format_repository ]
    tags:
      - { name: form.type, alias: page_media }


  page_media_set.media_set_definition:
    class: '%page_media_set.media_set_definition.class%'
    arguments: [ "%page_media_set.types%" ]
